#!/usr/bin/env bash

# Profile: $PROFILE_NAME
# Description: Brief description of the profile

# ===============================================
# Environment variables
# ===============================================
# export VARNAME=value

# set default text editor 
export EDITOR=vim

# ===============================================
# Path modifications
# ===============================================
# export PATH=$PATH:/new/path

# ===============================================
# Functions
# ===============================================
# functionname() {
#    command
# }

# ===============================================
# Aliases
# ===============================================
# alias aliasname='command'

# ===============================================
# Prompt modifications
# ===============================================
# PS1='Your custom prompt here'

# ===============================================
# Profile specific settings/commands
# ===============================================
# Add any profile-specific settings or commands here

# ===============================================
# Other
# ===============================================
# Add anything else here

# End of profile: $PROFILE_NAME

